baseURL: "/"
languageCode: "en-us"
title: "Mon blog automatique"
theme: "PaperMod"

module:
  imports:
    - path: github.com/adityatelange/hugo-PaperMod/v7

params:
  defaultTheme: auto
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  comments: false
  hidemeta: false

menu:
  main:
    - name: Articles
      url: /posts/
      weight: 1
